---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cnoriega20/ps-springcloudconfig-toll-system
          search-paths:
            - 'st*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/cnoriega20/ps-springcloud-configserver-git-perf
              search-paths:
                - 'st*'
